### ISSUE TITLE
Some minor fixes

### ISSUE THREAD

**Issue by mohamedmerrouch** [iddify/covidma-scraper-api#1]
I am using your api in my personal project. Now that I found you I will make sure to put your name in the sources and credits

I just wanted to make some comments about the results given by the api:

1- Deaths are now 1 while it should be 10
2- Daraa-Tafilalt and Dakhla-Oued Ed Dahab are missing

There is also a minor thing but worth mentioning. The data returned contains the unicode \u200b (zero_width_space) in some regions' data. I think it ll be better to parse them as Integers and returned them just like what you do with the Moroccan data.

**Comment by iddify** [comment]
Fixed!
